### ISSUE TITLE
Intu with PR #39 stops on Raspi

### ISSUE THREAD

**Issue by takaomoriyama** [watson-intu/self#41]
If new ABI is used as in PR https://github.com/watson-intu/self/pull/39, Intu on Raspi stops at the very beginning of the initialization process.

```
$ ./run_self.sh 
Configuring auto start of intu
Auto start of intu is already configured!
Running self..
./run_self2.sh: line 67:  5160 Segmentation fault      (core dumped) ./self_instance -P ${PLATFORM} "$@"
```

Backtrace:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `./self_instance -P raspi'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x75e1a2f8 in boost::filesystem::path::filename() const () from /home/pi/dev/takaomoriyama/self/bin/raspi/libboost_filesystem.so.1.62.0
[Current thread is 1 (Thread 0x6fa2e000 (LWP 5160))]

Thread 2 (Thread 0x6fa25640 (LWP 5161)):
#0  0x7586fd50 in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x72dac678 in ?? () from /lib/arm-linux-gnueabihf/libusb-1.0.so.0
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x6fa2e000 (LWP 5160)):
#0  0x75e1a2f8 in boost::filesystem::path::filename() const () from /home/pi/dev/takaomoriyama/self/bin/raspi/libboost_filesystem.so.1.62.0
No symbol table info available.
#1  0x75e13310 in boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*) () from /home/pi/dev/takaomoriyama/self/bin/raspi/libboost_filesystem.so.1.62.0
No symbol table info available.
#2  0x76bb5370 in boost::filesystem::create_directories (p=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/filesystem/operations.hpp:566
No locals.
#3  0x76bb3c3c in ValidateDirectory (a_Dir="./cache") at /home/pi/dev/takaomoriyama/self/src/SelfMain.cpp:42
No locals.
#4  0x76bb4650 in SelfMain (argc=3, argv=0x7efd4d24) at /home/pi/dev/takaomoriyama/self/src/SelfMain.cpp:262
        staticData = "./etc/"
        instanceData = "./"
        platform = "raspi"
        eConsoleLevel = LL_STATUS
        eFileLevel = LL_STATUS
        newPort = 0
        newGateway = ""
        newGroupId = ""
        newName = ""
        newToken = ""
        newOrganizationId = ""
        newProfile = ""
        bSetDevVersion = false
        bEnableDevVersion = false
        configFile = ""
#5  0x000109c4 in main (argc=3, argv=0x7efd4d24) at /home/pi/dev/takaomoriyama/self/src/main.cpp:35
No locals.
```

This does not occur if we use old ABI by specifying "add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)" for Raspi.

**Comment by takaomoriyama** [comment]
If we create directory "cache" before executing Intu, we can avoid error describe above, but another error occurs.

```
$ mkdir cache
$ ./run_self.sh  -c 0 -f 0
Configuring auto start of intu
Auto start of intu is already configured!
Running self..
[10/25/17 19:48:41.561][STAT][SelfInstance] Loaded config: ./config.json
[10/25/17 19:48:41.561][STAT][SelfInstance] Starting SelfInstance
[10/25/17 19:48:41.869][STAT][SelfGraph] Graph knowledge loaded (221 verts, 219 edges local)
[10/25/17 19:48:41.981][STAT][Library] Dynamic library libplatform_raspi.so loaded.
[10/25/17 19:48:42.026][STAT][Library] Dynamic library libopencv_plugin.so loaded.
[10/25/17 19:48:42.100][STAT][Library] Dynamic library librg_plugin.so loaded.
[10/25/17 19:48:42.283][STAT][Library] Dynamic library libwatson_plugin.so loaded.
[10/25/17 19:48:42.336][STAT][Library] Dynamic library libnexmo_plugin.so loaded.
[10/25/17 19:48:42.387][STAT][Library] Dynamic library libiva_plugin.so loaded.
[10/25/17 19:48:42.440][WARN][Alchemy] API-Key expected in user field.
[10/25/17 19:48:42.441][WARN][NaturalLanguageUnderstanding] User id expected in user field.
[10/25/17 19:48:42.441][WARN][NaturalLanguageUnderstanding] Password expected in password field
[10/25/17 19:48:42.441][DEBH][WEX] Url loaded as http://cap-sg-prd-1.integration.ibmcloud.com:17296/api
[10/25/17 19:48:42.441][WARN][RobotGateway] No bearer token provided, service will not start.
[10/25/17 19:48:42.442][WARN][Config] Failed to start service RobotGateway.
[10/25/17 19:48:42.442][DEBH][WeatherCompanyData] Starting WeatherCompanyData!
[10/25/17 19:48:42.443][DEBH][DeepQA] Url loaded as http://cap-sg-prd-1.integration.ibmcloud.com:15517/WatsonApp/deepqa
[10/25/17 19:48:42.444][DEBH][IVA] Starting IVA...
[10/25/17 19:48:42.467][WARN][Alchemy] API-Key expected in user field.
[10/25/17 19:48:42.467][DEBH][WeatherCompanyData] Starting WeatherLocation!
[10/25/17 19:48:42.468][WARN][SelfGraph] Failed to find service GraphV1
[10/25/17 19:48:42.468][WARN][SelfInstance] Failed to connect knowledge graph.
[10/25/17 19:48:42.469][STAT][TopicManager] Starting with selfId , bearer token 0 bytes
[10/25/17 19:48:42.471][DEBL][WebClientT] Connecting to 169.54.186.28:443
[10/25/17 19:48:42.476][STAT][WebServer] Listening on port 9443
[10/25/17 19:48:42.479][DEBH][TopicManager] New subscriber . to topic topic-manager.
[10/25/17 19:48:42.480][DEBH][TopicManager] New subscriber . to topic blackboard.
[10/25/17 19:48:42.481][DEBH][TopicManager] New subscriber . to topic gesture-manager.
[10/25/17 19:48:42.509][STAT][GestureManager] GestureManager started.
[10/25/17 19:48:42.509][STAT][SkillManager] SkillManager started.
[10/25/17 19:48:42.668][DEBL][WebClientT] Connecting to stream.watsonplatform.net:443
[10/25/17 19:48:42.670][DEBL][WebClientT] Failed to connect to 169.54.186.28:443
[10/25/17 19:48:42.671][DEBL][WebClientT] Failed to connect to 169.54.186.28:443: Connection refused
*** Error in `./self_instance': free(): invalid pointer: 0x007f1d4c ***
./run_self2.sh: line 67:  5300 Aborted                 (core dumped) ./self_instance -P ${PLATFORM} "$@"
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

Backtrace:
```
self_instance crash, backtrace:
...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `./self_instance -P raspi -c 0 -f 0'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
[Current thread is 1 (Thread 0x63e04640 (LWP 5324))]
...
Thread 1 (Thread 0x63e04640 (LWP 5324)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0 <repeats 32 times>}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x75803824 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {1873175512, 148, 0, 0, 1873175512, 523484026, 1996108768, 0, 1675639320, 1675639328, 1675639436, 1989715186, 1996093664, 1675639368, 1978087204, 8006, 1996089672, 1675639384, 1971168224, 1694, 1675639388, 1995959608, 1, 1971197492, 1694, 1971206148, 1996089672, 1675639352, 1, 72, 7, 7}}, sa_flags = 19, sa_restorer = 0x63e03a70}
        sigs = {__val = {32, 0 <repeats 31 times>}}
#2  0x7583cf78 in __libc_message (do_abort=do_abort@entry=2, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:175
        ap = {__ap = 0x63e03b6c}
        fd = 19
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = 120
#3  0x75843ad4 in malloc_printerr (action=<optimized out>, str=0x758f60f0 "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
        buf = "007f1d4c"
        cp = <optimized out>
        ar_ptr = <optimized out>
        ptr = <optimized out>
        str = 0x758f60f0 "free(): invalid pointer"
        action = <optimized out>
#4  0x75844514 in _int_free (av=0x75912794 <main_arena>, p=0x7f1d44, have_lock=<optimized out>) at malloc.c:3905
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
        __func__ = "_int_free"
#5  0x75ac7b90 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#6  0x76185d98 in WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >::HandleConnect (this=0x7f01c8, error=..., i=...) at /home/pi/dev/takaomoriyama/self/lib/cpp-sdk/src/utils/WebClient.cpp:470
No locals.
#7  0x7619ef7c in boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >::call<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > >, boost::system::error_code const, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > (this=0x63e03e74, u=..., b1=..., b2=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/bind/mem_fn_template.hpp:271
No locals.
#8  0x7619e0c8 in boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >::operator()<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > > (this=0x63e03e74, u=..., a1=..., a2=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/bind/mem_fn_template.hpp:286
        p = 0x0
#9  0x7619cf1c in boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > >::operator()<boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::rrlist1<boost::system::error_code const&> > (this=0x63e03e7c, f=..., a=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/bind/bind.hpp:398
No locals.
#10 0x7619b918 in boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >::operator()<boost::system::error_code const&> (this=0x63e03e74, a1=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/bind/bind.hpp:1306
        a = {a1_ = @0x63e03e90}
#11 0x7619a808 in boost::asio::detail::binder1<boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >, boost::system::error_code>::operator() (this=0x63e03e74) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/bind_handler.hpp:47
No locals.
#12 0x761990c8 in boost::asio::asio_handler_invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >, boost::system::error_code> > (function=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/handler_invoke_hook.hpp:69
No locals.
#13 0x76197a70 in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >, boost::system::error_code>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > > > (function=..., context=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/handler_invoke_helpers.hpp:37
No locals.
#14 0x7619646c in boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >, boost::system::error_code>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >, boost::system::error_code> (function=..., this_handler=0x63e03e74) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/bind_handler.hpp:88
No locals.
#15 0x761942f0 in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >, boost::system::error_code>, boost::asio::detail::binder1<boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > >, boost::system::error_code> > (function=..., context=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/handler_invoke_helpers.hpp:37
No locals.
#16 0x76192c20 in boost::asio::detail::reactive_socket_connect_op<boost::_bi::bind_t<void, boost::_mfi::mf2<void, WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > > > >::do_complete (owner=0x7f06f0, base=0x7f1b50) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/reactive_socket_connect_op.hpp:93
        b = {<boost::asio::detail::noncopyable> = {<No data fields>}, value_ = 1}
        o = 0x7f1b50
        p = {h = 0x63e03e74, v = 0x0, p = 0x0}
        handler = {handler_ = {f_ = {f_ = (void (WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >::*)(WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > * const, const boost::system::error_code &, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)) 0x76185a1c <WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >::HandleConnect(boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)>}, l_ = {<boost::_bi::storage3<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)(), boost::_bi::value<boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> > >> = {<boost::_bi::storage2<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > >, boost::arg<1> (*)()>> = {<boost::_bi::storage1<boost::_bi::value<boost::shared_ptr<WebClientT<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > > > >> = {a1_ = {t_ = {px = 0x7f01c8, pn = {pi_ = 0x7f04a0}}}}, <No data fields>}, a3_ = {t_ = {values_ = std::shared_ptr (count 2, weak 0) 0x7efc58, index_ = 0}}}, <No data fields>}}, arg1_ = {m_val = 111, m_cat = 0x75e39ce4 <boost::system::system_category()::system_category_const>}}
#17 0x76bf1ef4 in boost::asio::detail::task_io_service_operation::complete (this=0x7f1b50, owner=..., ec=..., bytes_transferred=0) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/task_io_service_operation.hpp:38
No locals.
#18 0x76bf3a50 in boost::asio::detail::epoll_reactor::descriptor_state::do_complete (owner=0x7f06f0, base=0x7ef6f0, ec=..., bytes_transferred=29) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/impl/epoll_reactor.ipp:651
        op = 0x7f1b50
        descriptor_data = 0x7ef6f0
        events = 29
#19 0x76bf1ef4 in boost::asio::detail::task_io_service_operation::complete (this=0x7ef6f0, owner=..., ec=..., bytes_transferred=29) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/task_io_service_operation.hpp:38
No locals.
#20 0x76d32fe8 in boost::asio::detail::task_io_service::do_run_one (this=0x7f06f0, lock=..., this_thread=..., ec=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/impl/task_io_service.ipp:372
        task_result = 29
        on_exit = {task_io_service_ = 0x7f06f0, lock_ = 0x63e03f68, this_thread_ = 0x63e03f7c}
        o = 0x7ef6f0
        more_handlers = true
#21 0x76d32cc4 in boost::asio::detail::task_io_service::run (this=0x7f06f0, ec=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/detail/impl/task_io_service.ipp:149
        this_thread = {<boost::asio::detail::thread_info_base> = {<boost::asio::detail::noncopyable> = {<No data fields>}, reusable_memory_ = 0x7f1b50}, private_op_queue = {<boost::asio::detail::noncopyable> = {<No data fields>}, front_ = 0x0, back_ = 0x0}, private_outstanding_work = 0}
        ctx = {<boost::asio::detail::noncopyable> = {<No data fields>}, key_ = 0x7f06f0, value_ = 0x63e03f7c, next_ = 0x0}
        lock = {<boost::asio::detail::noncopyable> = {<No data fields>}, mutex_ = @0x7f0708, locked_ = false}
        n = 2
#22 0x76d33270 in boost::asio::io_service::run (this=0x7f06a0) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/asio/impl/io_service.ipp:59
        ec = {m_val = 0, m_cat = 0x75e39ce4 <boost::system::system_category()::system_category_const>}
        s = 1996012304
#23 0x761b6144 in boost::_mfi::mf0<unsigned int, boost::asio::io_service>::operator() (this=0x7f08b4, p=0x7f06a0) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/bind/mem_fn_template.hpp:49
No locals.
#24 0x761b6060 in boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned int, boost::_mfi::mf0<unsigned int, boost::asio::io_service>, boost::_bi::list0> (this=0x7f08bc, f=..., a=...) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/bind/bind.hpp:249
No locals.
#25 0x761b6000 in boost::_bi::bind_t<unsigned int, boost::_mfi::mf0<unsigned int, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >::operator() (this=0x7f08b4) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/bind/bind.hpp:1294
        a = {<No data fields>}
#26 0x761b5fb4 in boost::detail::thread_data<boost::_bi::bind_t<unsigned int, boost::_mfi::mf0<unsigned int, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >::run (this=0x7f0798) at /home/pi/.local/share/qi/toolchains/raspi/boost/boost/thread/detail/thread.hpp:116
No locals.
#27 0x75e0b6cc in thread_proxy () from /home/pi/dev/takaomoriyama/self/bin/raspi/libboost_thread.so.1.62.0
No symbol table info available.
#28 0x75d91fc4 in start_thread (arg=0x63e04640) at pthread_create.c:335
        pd = 0x63e04640
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {1067758521, 698215525, 1675642432, 2127150856, 0, 338, 2127150856, 4096, 1, 1675641212, 0 <repeats 54 times>}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#29 0x758a7c68 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
No locals.
```

**Comment by takaomoriyama** [comment]
This issue seems to be caused by ABI mismatch with Intu code and libboost library which is provided as DLL in lib/self-raspi. Removing these binaries and use of system library solved the issue.
